### ISSUE TITLE
第四关最上面一行,移动异常

### ISSUE THREAD

**Issue by Kprunning** [Kprunning/CrampedRoomOfDeath-Practicerc#3]
TypeError: Cannot read properties of undefined (reading 'x')
    at PlayerManager.checkMoveDirect (PlayerManager.ts:365:27)
    at PlayerManager.willBlock (PlayerManager.ts:279:19)
    at PlayerManager.inputHandle (PlayerManager.ts:129:14)
    at EventManager.ts:38:20
    at Array.forEach (<anonymous>)
    at EventManager.emit (EventManager.ts:37:15)
    at ControlManager.handleCtrl (ControlManager.ts:10:27)
    at EventHandler.emit (component-event-handler.ts:174:17)
    at Function.emitEvents (component-event-handler.ts:88:19)
    at Button._onTouchEnded (button.ts:880:35)

**Comment by Kprunning** [comment]
漏写了一个x的赋值逻辑
